name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load instance with '...'
        2. Convert with parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The conversion should complete successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The conversion failed with error...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message/Stack Trace
      description: If applicable, provide the full error message and stack trace
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "...", line X, in <module>
            ...
        Error: ...

  - type: input
    id: version
    attributes:
      label: XBridge Version
      description: What version of XBridge are you using?
      placeholder: "1.5.0rc2"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system?
      placeholder: "Ubuntu 22.04, macOS 14.0, Windows 11, etc."

  - type: textarea
    id: taxonomy
    attributes:
      label: Taxonomy Information
      description: Information about the taxonomy you're using
      placeholder: |
        EBA Taxonomy version: 4.1
        Taxonomy file: FullTaxonomy.7z

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - File size: 10MB
        - Number of facts: 5000
        - Any other relevant information

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using a supported version of XBridge (1.1.x or higher)
          required: true
        - label: I have included all relevant information above
          required: true
