"""Module holding the Converter class, which converts from XBRL-XML to XBRL-CSV
taking as input the taxonomy object and the instance object
"""

from __future__ import annotations

import csv
import json
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from shutil import rmtree
from tempfile import TemporaryDirectory
from typing import Any, Dict, List, Optional, Union
from zipfile import ZipFile

import pandas as pd

from xbridge.exceptions import (
    DecimalValueError,
    FactReconciliationError,
    FactReconciliationWarning,
    FilingIndicatorValueError,
    FilingIndicatorWarning,
    MultipleBaseCurrenciesError,
)
from xbridge.instance import CsvInstance, Instance, XmlInstance
from xbridge.modules import Module, Table

INDEX_FILE = Path(__file__).parent / "modules" / "index.json"

if not INDEX_FILE.exists():
    raise ValueError(
        "Cannot find the index file for the modules. "
        "Please make sure that the index file and the "
        "JSON files with the mappings exist in the modules folder."
    )

with open(INDEX_FILE, "r", encoding="utf-8") as fl:
    index: Dict[str, str] = json.load(fl)

# Infinite precision has two spellings across the XBRL formats.  xBRL-CSV 1.0
# REC section 3.1.9 accepts only an integer or the special value "#none"
# (meaning infinity); "INF" is the xBRL-XML lexical form and is rejected by a
# conformant xBRL-CSV processor with xbrlce:invalidDecimalsValue.  Source
# instances are xBRL-XML, so "INF" is canonicalised to "#none" on the way out.
XML_INFINITE_DECIMALS = "INF"
CSV_INFINITE_DECIMALS = "#none"


@dataclass
class FactReconciliation:
    """Post-conversion accounting of every source fact.

    The core invariant is::

        source_facts == converted + excluded_non_reported + unmatched

    where each detected fact ends up in exactly one bucket. ``unmatched`` and
    ``unrecognized_elements`` represent facts lost *silently* — the former
    detected but matching no table, the latter never recognised as facts at all.
    A balanced reconciliation with no unrecognised elements means nothing was
    dropped.
    """

    source_facts: int = 0
    converted: int = 0
    excluded_non_reported: int = 0
    unmatched: int = 0
    unrecognized_elements: List[str] = field(default_factory=list)

    @property
    def is_consistent(self) -> bool:
        """Defensive accounting check: every detected fact lands in exactly one bucket.

        ``unmatched`` is computed as the remainder, so this should always hold; a
        False result signals a counting bug (e.g. a fact double-counted as both
        converted and orphaned). It says nothing about whether facts were lost —
        use :attr:`has_silent_loss` for that.
        """
        return (
            self.unmatched >= 0
            and self.source_facts == self.converted + self.excluded_non_reported + self.unmatched
        )

    @property
    def has_silent_loss(self) -> bool:
        """True when facts were dropped without an explicit filing-indicator reason.

        Covers detected facts that matched no table (``unmatched``) and top-level
        elements never recognised as facts (``unrecognized_elements``). Orphaned
        facts (``excluded_non_reported``) are *not* silent — they have their own
        filing-indicator report — so they do not count here.
        """
        return self.unmatched > 0 or bool(self.unrecognized_elements)


#: Value of the ``unit`` dimension of a datapoint whose unit is taken from the
#: ``baseCurrency`` report parameter instead of the table's ``unit`` column.
BASE_CURRENCY_UNIT_REF = "$baseCurrency"

#: Prefix of the unit measures that denote an ISO 4217 currency.
_ISO_CURRENCY_PREFIX = "iso4217:"


@dataclass
class BaseCurrencyEvidence:
    """Facts that pin the ``baseCurrency`` parameter to one currency.

    Attributes:
        currency: The unit measure of the facts (e.g. ``"iso4217:EUR"``).
        fact_count: How many facts were reported in this currency.
        example_table: Code of a table where such a fact was found.
        example_datapoint: Code of one of those datapoints, to ease
            locating the offending facts in the source instance.
    """

    currency: str
    fact_count: int = 0
    example_table: Optional[str] = None
    example_datapoint: Optional[str] = None


class Converter:
    """Converter different types of files into others, using the EBA
    :obj:`taxonomy <xbridge.taxonomy.Taxonomy>` and XBRL-instance. Each file is extracted and saved
    in a temporary directory.
    Then, these files are converted into JSON and again saved in a
    compressed folder such as ZIP or 7z.

    :obj:`Variables <xbridge.taxonomy.Variable>` are generated by combining the open keys
    column with the attributes found within the taxonomy
    :obj:`modules <xbridge.taxonomy.Module>`.
    Then, variable's dimension is extracted
    from it with the purpose to be used with the context
    coming from the ``XML_instance``,
    to create the :obj:`scenario <xbridge.xml_instance.Scenario>`.

    Finally, an inner join is done between the variables
    created and the values from the facts
    of the ``XML_instance`` :obj:`context <xbridge.xml_instance.Context>`.

    """

    def __init__(self, instance_path: Union[str, Path]) -> None:
        path_str = str(instance_path)
        inst = Instance.from_path(path_str)
        module_ref = getattr(inst, "module_ref", None)
        if not isinstance(module_ref, str):
            inst = Instance(path_str)
            module_ref = getattr(inst, "module_ref", None)
        self.instance = inst

        if not module_ref:
            raise ValueError("No module_ref found in the instance.")
        if module_ref not in index:
            raise ValueError(f"Module {module_ref} not found in the taxonomy index")

        module_path = Path(__file__).parent / "modules" / index[module_ref]
        self.module = Module.from_serialized(module_path)
        self._reported_tables: list[str] = []
        self._decimals_parameters: dict[str, Union[int, str]] = {}
        # Currencies of the reported facts that take their unit from the
        # baseCurrency parameter, keyed by unit measure. Filled while the
        # tables are converted; a well-formed instance yields exactly one.
        self._base_currency_candidates: dict[str, BaseCurrencyEvidence] = {}
        # Populated by _validate_filing_indicators during an XML conversion so
        # callers can inspect exactly how many facts reached the output.
        self.reconciliation: Optional[FactReconciliation] = None

    def convert(
        self,
        output_path: Union[str, Path],
        headers_as_datapoints: bool = False,
        validate_filing_indicators: bool = True,
        strict_validation: bool = False,
    ) -> Path:
        """Convert the ``XML Instance`` to a CSV file or between CSV formats"""
        if not output_path:
            raise ValueError("Output path not provided")

        if isinstance(output_path, str):
            output_path = Path(output_path)
        if self.instance is None:
            raise ValueError("Instance not provided")

        if self.module is None:
            raise ValueError("Module of the instance file not found in the taxonomy")

        if isinstance(self.instance, XmlInstance):
            return self.convert_xml(
                output_path, headers_as_datapoints, validate_filing_indicators, strict_validation
            )
        elif isinstance(self.instance, CsvInstance):
            if self.module.architecture != "headers":
                raise ValueError("Cannot convert CSV instance with non-headers architecture")
            return self.convert_csv(output_path)
        else:
            raise ValueError("Invalid instance type")

    def convert_xml(
        self,
        output_path: Path,
        headers_as_datapoints: bool = False,
        validate_filing_indicators: bool = True,
        strict_validation: bool = True,
    ) -> Path:
        module_filind_codes = [table.filing_indicator_code for table in self.module.tables]

        filing_indicator_codes = (
            self.instance.filing_indicators if self.instance.filing_indicators else []
        )

        for filing_indicator in filing_indicator_codes:
            if filing_indicator.table not in module_filind_codes:
                raise ValueError(
                    f"Filing indicator {filing_indicator.table} not found in the module tables."
                )

        instance_path_stem = Path(str(self.instance.path)).stem

        temp_dir = TemporaryDirectory()
        temp_dir_path = Path(temp_dir.name)

        meta_inf_dir = temp_dir_path / instance_path_stem / "META-INF"
        report_dir = temp_dir_path / instance_path_stem / "reports"

        meta_inf_dir.mkdir(parents=True)
        report_dir.mkdir(parents=True)

        with open(meta_inf_dir / "reportPackage.json", "w", encoding="UTF-8") as fl:
            json.dump(
                {"documentInfo": {"documentType": "https://xbrl.org/report-package/2023"}},
                fl,
            )

        with open(report_dir / "report.json", "w", encoding="UTF-8") as fl:
            json.dump(
                {
                    "documentInfo": {
                        "documentType": "https://xbrl.org/2021/xbrl-csv",
                        "extends": [self.module.url],
                    }
                },
                fl,
            )

        self._convert_filing_indicator(report_dir)

        if validate_filing_indicators:
            self._validate_filing_indicators(strict_validation=strict_validation)

        self._convert_tables(report_dir, headers_as_datapoints)
        self._convert_parameters(report_dir)

        file_name = instance_path_stem + ".zip"

        zip_file_path = output_path / file_name

        with ZipFile(zip_file_path, "w") as zip_fl:
            for file in meta_inf_dir.iterdir():
                zip_fl.write(file, arcname=f"{instance_path_stem}/META-INF/{file.name}")
            for file in report_dir.iterdir():
                zip_fl.write(file, arcname=f"{instance_path_stem}/reports/{file.name}")

        temp_dir.cleanup()

        return zip_file_path

    def convert_csv(self, output_path: Path) -> Path:
        for table_file in self.instance.table_files:
            table_url = table_file.name
            for table in self.module.tables:
                if table.url == table_url:
                    table_columns = table.columns
                    open_keys_mapping = table._open_keys_mapping
                    break
            else:
                raise ValueError(f"Table {table_url} not found in the module")

            table_df = pd.read_csv(table_file)
            # For type 't' datapoints is only accepted 'true' as value
            # but pandas convert it directly to 'True'.
            # For the rest of boolean datapoints 'true' is also accepted
            table_df = table_df.replace(True, "true")

            columns_rename = {
                f"c{column_code}": property_code
                for property_code, column_code in open_keys_mapping.items()
            }
            table_df.rename(columns=columns_rename, inplace=True)
            open_keys_properties = list(columns_rename.values())
            measure_columns = [
                column["code"] for column in table_columns if column["code"] not in columns_rename
            ]
            measure_columns = [column for column in measure_columns if column in table_df.columns]

            table_df = table_df.melt(id_vars=open_keys_properties, value_vars=measure_columns)

            mapping_dict = {
                column["code"]: f"dp{column['variable_id']}" for column in table_columns
            }
            mapping_df = pd.DataFrame(mapping_dict.items(), columns=["variable", "datapoint"])
            table_df = pd.merge(mapping_df, table_df, on="variable", how="inner")

            table_df.drop(columns=["variable"], inplace=True)
            table_df.rename(columns={"value": "factValue"}, inplace=True)

            table_df.to_csv(table_file, index=False)

        file_name = self.instance.path.name
        zip_file_path = output_path / file_name

        root = self.instance._root_folder

        temp_dir = self.instance.temp_dir_path
        if temp_dir is None:
            raise ValueError("CSV instance has no temp dir path")

        meta_inf_dir = temp_dir / "META-INF"
        report_dir = temp_dir / "reports"

        with ZipFile(zip_file_path, "w") as zip_fl:
            for file in meta_inf_dir.iterdir():
                zip_fl.write(file, arcname=f"{root}/META-INF/{file.name}")
            for file in report_dir.iterdir():
                zip_fl.write(file, arcname=f"{root}/reports/{file.name}")

        rmtree(temp_dir)

        return zip_file_path

    def _get_instance_df(self, table: Table) -> pd.DataFrame:
        """Returns the dataframe with the subset of instace facts applicable to the table"""
        if self.instance.instance_df is None:
            return pd.DataFrame(columns=["datapoint", "value"])
        instance_columns = set(self.instance.instance_df.columns)
        variable_columns = set(table.variable_columns or [])
        open_keys = set(table.open_keys)
        attributes = set(table.attributes)

        # If any open key is not in the instance, then the table cannot have
        # any datapoint
        if not open_keys.issubset(instance_columns):
            return pd.DataFrame(columns=["datapoint", "value"] + list(open_keys))

        # Determine the not relevant dims
        not_relevant_dims = (
            instance_columns
            - variable_columns
            - open_keys
            - attributes
            - {"value", "unit", "decimals"}
        )

        # Convert to list so Pandas won't complain
        # "unit" is always kept: even when the table has no unit column, the
        # unit of the facts is needed to determine the base currency.
        needed_columns = list(
            variable_columns
            | open_keys
            | attributes
            | {"value", "decimals", "unit"}
            | not_relevant_dims
        )

        # Intersect with instance_columns as a list
        needed_columns = list(set(needed_columns).intersection(instance_columns))

        instance_df = self.instance.instance_df[needed_columns].copy()

        # Drop datapoints that have non-null values in not relevant dimensions
        # And drop the not relevant columns
        if not_relevant_dims:
            # Convert to list
            nrd_list = list(not_relevant_dims)
            # Create mask to filter out rows where not relevant dimensions have non-null values
            mask = instance_df[nrd_list].isnull().all(axis=1)
            instance_df = instance_df.loc[mask]
            instance_df.drop(columns=nrd_list, inplace=True)

        # Rows missing values for required open keys do not belong to the table
        if open_keys:
            instance_df.dropna(subset=list(open_keys), inplace=True)

        return instance_df

    def _matching_fact_indices(self, table: Table) -> set[int]:
        """Return indices of instance facts that actually match the table definition."""
        if self.instance.instance_df is None:
            return set()

        instance_df = self._get_instance_df(table)
        if instance_df.empty or table.variable_df is None:
            return set()

        variable_columns = set(table.variable_columns or [])
        open_keys = set(table.open_keys)

        # self.instance.instance_df is guaranteed to not be None due to check at line 296
        instance_columns = set(self.instance.instance_df.columns)

        datapoint_df = table.variable_df.copy()

        # Handle missing columns by filtering datapoint_df (same as _variable_generator)
        # This prevents requiring dimensions that don't exist in the instance
        missing_cols = list(variable_columns - instance_columns)
        if "data_type" in missing_cols:
            missing_cols.remove("data_type")
        if missing_cols:
            mask = datapoint_df[missing_cols].isnull().all(axis=1)
            datapoint_df = datapoint_df.loc[mask]
            datapoint_df = datapoint_df.drop(columns=missing_cols)

        # Match on all variable columns (dimensions) to avoid Cartesian product
        # explosion. Consistent with _variable_generator() to prevent OOM.
        merge_cols = list(variable_columns & instance_columns)

        instance_df = instance_df.copy()
        instance_df["_idx"] = instance_df.index

        merged_df = pd.merge(datapoint_df, instance_df, on=merge_cols, how="inner")

        if open_keys:
            valid_open_keys = [key for key in open_keys if key in merged_df.columns]
            if valid_open_keys:
                merged_df.dropna(subset=valid_open_keys, inplace=True)

        return set(merged_df["_idx"].tolist())

    def _variable_generator(self, table: Table) -> pd.DataFrame:
        """Returns the dataframe with the CSV file for the table

        :param table: The table we use.

        """
        instance_df = self._get_instance_df(table)
        if instance_df.empty or table.variable_df is None:
            # The unit is kept by _get_instance_df for the base currency
            # detection, but it is only an output column where the table
            # declares it as an attribute.
            if "unit" not in table.attributes and "unit" in instance_df.columns:
                instance_df = instance_df.drop(columns=["unit"])
            return instance_df

        variable_columns = set(table.variable_columns or [])

        open_keys = set(table.open_keys)
        instance_columns = (
            set(self.instance.instance_df.columns)
            if self.instance.instance_df is not None
            else set()
        )

        # Do the intersection and drop from datapoints the columns and records
        datapoint_df = table.variable_df.copy()
        missing_cols = list(variable_columns - instance_columns)
        if "data_type" in missing_cols:
            missing_cols.remove("data_type")
        if missing_cols:
            mask = datapoint_df[missing_cols].isnull().all(axis=1)
            datapoint_df = datapoint_df.loc[mask]
            datapoint_df = datapoint_df.drop(columns=missing_cols)

        # Join the dataframes on the datapoint_columns
        merge_cols = list(variable_columns & instance_columns)

        table_df = pd.merge(datapoint_df, instance_df, on=merge_cols, how="inner")

        if "data_type" in table_df.columns and "decimals" in table_df.columns:
            decimals_table = table_df[["decimals", "data_type"]].drop_duplicates()
            for _, row in decimals_table.iterrows():
                if not row["data_type"] or not row["decimals"]:
                    continue

                data_type = row["data_type"][1:]
                decimals = row["decimals"]
                normalized_decimals = self._normalize_decimals_value(decimals)

                if data_type not in self._decimals_parameters:
                    self._decimals_parameters[data_type] = normalized_decimals
                else:
                    # Skip infinity when we already have an entry,
                    # as numeric values take precedence.
                    if normalized_decimals == CSV_INFINITE_DECIMALS:
                        continue

                    existing_value = self._decimals_parameters[data_type]
                    if existing_value == CSV_INFINITE_DECIMALS or (
                        isinstance(existing_value, int)
                        and isinstance(normalized_decimals, int)
                        and normalized_decimals < existing_value
                    ):
                        self._decimals_parameters[data_type] = normalized_decimals

            drop_columns = merge_cols + ["data_type", "decimals"]
        else:
            drop_columns = merge_cols

        # Also drop allowed_values if present (it's metadata, not data)
        if "allowed_values" in table_df.columns:
            drop_columns.append("allowed_values")

        # The facts whose datapoint takes its unit from the baseCurrency
        # parameter tell us which currency that parameter must hold.
        self._collect_base_currency_evidence(table, table_df)

        # Clear unit for rows where variable didn't have unit in dimensions
        if "_has_unit_dim" in table_df.columns:
            if "unit" in table.attributes and "unit" in table_df.columns:
                table_df.loc[~table_df["_has_unit_dim"], "unit"] = pd.NA
            drop_columns.append("_has_unit_dim")

        if "_unit_ref" in table_df.columns:
            drop_columns.append("_unit_ref")

        # The unit is only an output column for tables that declare it
        if "unit" not in table.attributes and "unit" in table_df.columns:
            drop_columns.append("unit")

        table_df.drop(columns=drop_columns, inplace=True)

        # Drop the datapoints that have null values in the open keys
        valid_open_keys = [key for key in open_keys if key in table_df.columns]
        if valid_open_keys:
            table_df.dropna(subset=valid_open_keys, inplace=True)

        if "unit" in table.attributes and "unit" in table_df.columns and self.instance.units:
            table_df["unit"] = table_df["unit"].map(self.instance.units, na_action="ignore")

        return table_df

    def _collect_base_currency_evidence(self, table: Table, table_df: pd.DataFrame) -> None:
        """Records the currencies of the facts that fix the base currency.

        The taxonomy JSON states, for every datapoint, where its unit comes
        from: ``"unit": "$unit"`` means the unit is reported in the table's
        ``unit`` column, ``"unit": "$baseCurrency"`` means it is taken from the
        ``baseCurrency`` report parameter, and datapoints without a ``unit``
        dimension are not monetary.  In XBRL-XML every monetary fact carries
        its own unit, so the currency of the facts of the second kind is the
        one the ``baseCurrency`` parameter has to hold.

        :param table: The table being converted.
        :param table_df: The facts of the table, joined with their datapoints.
        """
        if "_unit_ref" not in table_df.columns or "unit" not in table_df.columns:
            return

        units = self.instance.units or {}
        base_currency_rows = table_df.loc[
            (table_df["_unit_ref"] == BASE_CURRENCY_UNIT_REF) & table_df["unit"].notna()
        ]
        if base_currency_rows.empty:
            return

        for unit_id, fact_count in base_currency_rows["unit"].value_counts().items():
            measure = units.get(str(unit_id), str(unit_id))
            if not measure.lower().startswith(_ISO_CURRENCY_PREFIX):
                continue
            evidence = self._base_currency_candidates.get(measure)
            if evidence is None:
                example = base_currency_rows.loc[base_currency_rows["unit"] == unit_id].iloc[0]
                evidence = BaseCurrencyEvidence(
                    currency=measure,
                    example_table=table.code,
                    example_datapoint=str(example.get("datapoint")),
                )
                self._base_currency_candidates[measure] = evidence
            evidence.fact_count += int(fact_count)

    def _resolve_base_currency(self) -> Optional[str]:
        """Returns the base currency of the instance, or ``None`` if unknown.

        :raises MultipleBaseCurrenciesError: If the reported facts point to
            more than one base currency, which makes the instance erroneous.
        """
        candidates = self._base_currency_candidates

        if len(candidates) > 1:
            detail = "; ".join(
                (
                    f"{evidence.currency} ({evidence.fact_count} facts, e.g. datapoint "
                    f"{evidence.example_datapoint} in table {evidence.example_table})"
                )
                for evidence in sorted(candidates.values(), key=lambda item: item.currency)
            )
            raise MultipleBaseCurrenciesError(
                (
                    "The instance reports facts in more than one base currency: "
                    f"{detail}. The facts whose datapoint takes its unit from the "
                    "baseCurrency parameter must all use the reporting currency; "
                    "amounts in other currencies belong to the datapoints that "
                    "report their unit explicitly. The instance is erroneous and "
                    "has not been converted."
                ),
                currencies=sorted(candidates),
            )

        if candidates:
            return next(iter(candidates))

        ##Workaround
        # No reported fact pins the base currency (no monetary datapoint taking
        # its unit from the parameter was reported). We fall back to the first
        # currency declared in the instance units, which is what the parameter
        # would have to be if such a datapoint were reported.
        return self.instance.base_currency

    def _normalize_decimals_value(self, decimals: Any) -> Union[int, str]:
        """Return a validated decimals value or raise a DecimalValueError.

        Both spellings of infinity are accepted on input, but infinity is
        always returned as the xBRL-CSV special value ``#none`` so that the
        rest of the conversion — and the generated ``parameters.csv`` — never
        carries the xBRL-XML ``INF`` spelling.
        """
        candidate = decimals
        if isinstance(candidate, str):
            candidate = candidate.strip()

        if candidate in {XML_INFINITE_DECIMALS, CSV_INFINITE_DECIMALS}:
            return CSV_INFINITE_DECIMALS

        try:
            return int(candidate)
        except (TypeError, ValueError) as exc:
            raise DecimalValueError(
                f"Invalid decimals value: {decimals}, should be integer, "
                f"'{XML_INFINITE_DECIMALS}' or '{CSV_INFINITE_DECIMALS}'",
                offending_value=decimals,
            ) from exc

    def _convert_tables(
        self,
        temp_dir_path: Path,
        headers_as_datapoints: bool,
    ) -> None:
        for table in self.module.tables:
            ##Workaround:
            # To calculate the table code for abstract tables, we look whether the name
            # ends with a letter, and if so, we remove the last part of the code
            # Possible alternative: add metadata mapping abstract and concrete tables to
            # avoid doing this kind of corrections
            # Defining the output path and check if the table is reported

            if table.filing_indicator_code not in self._reported_tables:
                continue

            datapoints = self._variable_generator(table)

            if datapoints.empty:
                continue

            # if table.architecture == 'datapoints':

            # Cleaning up the dataframe and sorting it
            datapoints = datapoints.rename(columns={"value": "factValue"})
            # Workaround
            # The enumerated key dimensions need to have a prefix like the one
            # Defined by the EBA in the JSON files. We take them from the taxonomy
            # Because EBA is using exactly those for the JSON files.

            datapoints.sort_values(by=["datapoint"], ascending=True, inplace=True)
            output_path_table = temp_dir_path / (table.url or "table.csv")

            export_index = False

            if table.architecture == "headers" and not headers_as_datapoints:
                datapoint_column_df = pd.DataFrame(table.columns, columns=["code", "variable_id"])
                datapoint_column_df.rename(
                    columns={"variable_id": "datapoint", "code": "column_code"},
                    inplace=True,
                )
                open_keys_mapping = {k: f"c{v}" for k, v in table._open_keys_mapping.items()}
                datapoints.rename(columns=open_keys_mapping, inplace=True)
                datapoints = pd.merge(datapoint_column_df, datapoints, on="datapoint", how="inner")
                if not table.open_keys:
                    datapoints["index"] = 0
                    index = "index"
                else:
                    index = list(open_keys_mapping.values())  # type: ignore[assignment]
                    export_index = True
                datapoints = datapoints.pivot(
                    index=index, columns="column_code", values="factValue"
                )

            elif table.architecture == "headers" and headers_as_datapoints:
                datapoints["datapoint"] = "dp" + datapoints["datapoint"].astype(str)

            datapoints.to_csv(output_path_table, index=export_index)

    def _convert_filing_indicator(self, temp_dir_path: Path) -> None:
        # Workaround;
        # Developed for the EBA structure
        output_path_fi = temp_dir_path / "FilingIndicators.csv"
        if self.instance.filing_indicators is None:
            return
        filing_indicators = self.instance.filing_indicators

        with output_path_fi.open("w", newline="", encoding="utf-8") as fl:
            csv_writer = csv.writer(fl)
            csv_writer.writerow(["templateID", "reported"])
            for fil_ind in filing_indicators:
                value = "true" if fil_ind.value else "false"
                csv_writer.writerow([fil_ind.table, value])
                if fil_ind.value and fil_ind.table:
                    self._reported_tables.append(fil_ind.table)

    def _validate_filing_indicators(self, strict_validation: bool = True) -> None:
        """Validate filing indicators and reconcile every source fact.

        Two checks share this single pass over the facts:

        * **Orphaned facts** — facts belonging only to non-reported tables are
          excluded from the output; reported via :class:`FilingIndicatorWarning`
          / :class:`FilingIndicatorValueError`.
        * **Fact reconciliation** — a census (stored on :attr:`reconciliation`)
          confirming that every detected fact was either converted or has an
          explicit reason for exclusion. Facts matching no table ("unmatched")
          and elements never recognised as facts ("unrecognized") are silent
          losses, reported via :class:`FactReconciliationWarning` /
          :class:`FactReconciliationError`.

        Raises:
            FilingIndicatorValueError: Under strict validation, if facts belong
                only to tables with ``filed=false``.
            FactReconciliationError: Under strict validation, if facts were lost
                silently (unmatched or unrecognised).
        """
        unrecognized = list(self.instance.unrecognized_fact_elements)

        if self.instance.instance_df is None or self.instance.instance_df.empty:
            self.reconciliation = FactReconciliation(unrecognized_elements=unrecognized)
            self._report_reconciliation(strict_validation)
            return

        instance_df = self.instance.instance_df

        # Step 1: Track which facts belong to ANY reported table without materializing a huge set
        reported_mask = pd.Series(False, index=instance_df.index)
        for table in self.module.tables:
            if table.filing_indicator_code in self._reported_tables:
                reported_indices = self._matching_fact_indices(table)
                if reported_indices:
                    reported_mask.loc[list(reported_indices)] = True

        # Step 2: Find facts that belong ONLY to non-reported tables
        orphaned_mask = pd.Series(False, index=instance_df.index)
        orphaned_per_table = {}

        for table in self.module.tables:
            if table.filing_indicator_code not in self._reported_tables:
                orphaned_indices = self._matching_fact_indices(table)
                if orphaned_indices:
                    # Facts in this table that never appear in a reported table
                    orphaned_in_this_table = [
                        idx for idx in orphaned_indices if not reported_mask.loc[idx]
                    ]
                    if orphaned_in_this_table:
                        orphaned_mask.loc[orphaned_in_this_table] = True
                        orphaned_per_table[table.filing_indicator_code] = len(
                            orphaned_in_this_table
                        )

        total_orphaned = int(orphaned_mask.sum())

        # Build the fact census from the masks already computed above. converted
        # and excluded are disjoint (a fact reported by any table is never
        # counted as orphaned), so the remainder are facts that matched no table
        # at all and are dropped without any filing-indicator explanation.
        source_facts = len(instance_df)
        converted = int(reported_mask.sum())
        unmatched = source_facts - converted - total_orphaned
        self.reconciliation = FactReconciliation(
            source_facts=source_facts,
            converted=converted,
            excluded_non_reported=total_orphaned,
            unmatched=unmatched,
            unrecognized_elements=unrecognized,
        )

        if total_orphaned:
            error_msg = (
                f"Filing indicator inconsistency detected:\n"
                f"Found {total_orphaned} fact(s) that belong ONLY"
                f" to non-reported tables:\n"
            )
            for table_code, count in orphaned_per_table.items():
                error_msg += f"  - {table_code}: {count} fact(s)\n"

            if strict_validation:
                error_msg += (
                    "\nThe conversion process will not continue due to strict validation mode. "
                    "Either set filed=true for the relevant tables "
                    "or remove these facts from the XML."
                )
                raise FilingIndicatorValueError(error_msg, orphaned_per_table)
            error_msg += (
                "\nThese facts will be excluded from the output. "
                "Consider setting filed=true for the relevant tables "
                "or removing these facts from the XML."
            )
            warnings.warn(
                error_msg,
                category=FilingIndicatorWarning,
                stacklevel=2,
            )

        self._report_reconciliation(strict_validation)

    def _report_reconciliation(self, strict_validation: bool) -> None:
        """Warn (or raise, under strict validation) when the census shows a silent loss.

        "Silent" means facts absent from the output without a filing-indicator
        reason: detected facts matching no table, or top-level elements never
        recognised as facts. Orphaned facts have their own dedicated report and
        are not repeated here.
        """
        reconciliation = self.reconciliation
        if reconciliation is None or not reconciliation.has_silent_loss:
            return

        lines = ["Fact reconciliation detected facts missing from the output:"]
        if reconciliation.unmatched:
            lines.append(
                f"  - {reconciliation.unmatched} detected fact(s) matched no table "
                "definition and were not written to any output file."
            )
        if reconciliation.unrecognized_elements:
            shown = ", ".join(reconciliation.unrecognized_elements[:10])
            hidden = len(reconciliation.unrecognized_elements) - 10
            if hidden > 0:
                shown += f", … (+{hidden} more)"
            lines.append(
                f"  - {len(reconciliation.unrecognized_elements)} top-level element type(s) "
                f"were not recognised as facts or XBRL infrastructure: {shown}"
            )
        message = "\n".join(lines)

        if strict_validation:
            message += (
                "\nThe conversion process will not continue due to strict validation mode. "
                "Verify the instance namespaces and that the taxonomy version matches."
            )
            raise FactReconciliationError(message, reconciliation)
        message += (
            "\nThese facts are absent from the output. "
            "Verify the instance namespaces and that the taxonomy version matches."
        )
        warnings.warn(
            message,
            category=FactReconciliationWarning,
            stacklevel=2,
        )

    def _convert_parameters(self, temp_dir_path: Path) -> None:
        # Workaround;
        # Developed for the EBA structure
        output_path_parameters = temp_dir_path / "parameters.csv"
        parameters: Dict[str, Any] = {
            "entityID": self.instance.entity,
            "refPeriod": self.instance.period,
        }

        # Only include baseCurrency if it is present in the instance
        base_currency = self._resolve_base_currency()
        if base_currency is not None:
            parameters["baseCurrency"] = base_currency

        for data_type, decimals in self._decimals_parameters.items():
            parameters[data_type] = decimals

        with open(output_path_parameters, "w", newline="", encoding="utf-8") as fl:
            csv_writer = csv.writer(fl)
            csv_writer.writerow(["name", "value"])
            for k, v in parameters.items():
                csv_writer.writerow([k, v])
