name: Publish package

on:
  release:
    types: [created]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pipenv install --dev
      - name: Build package
        run: pipenv run python setup.py sdist
      - name: Publish to PyPI
        run: pipenv run twine upload dist/*